// Vcard properties based on version 4
package prop

const (
	// Static properties
	START_PROP = "BEGIN:VCARD"
	END_PROP   = "END:VCARD"

	// Tokens
	ADR          = "ADR"
	ANNIVERSARY  = "ANNIVERSARY"
	BDAY         = "BDAY"
	CALADRURI    = "CALADRURI"
	CALURI       = "CALURI"
	CATEGORIES   = "CATEGORIES"
	CALSS        = "CLASS"
	CLIENTPIDMAP = "CLIENTPIDMAP"
	EMAIL        = "EMAIL"
	FBURL        = "FBURL"
	FN           = "FN"
	GENDER       = "GENDER"
	GEO          = "GEO"
	IMPP         = "IMPP"
	KEY          = "KEY"
	KIND         = "KIND"
	LANG         = "LANG"
	LOGO         = "LOGO"
	MAILER       = "MAILER"
	MEMBER       = "MEMBER"
	N            = "N"
	NAME         = "NAME"
	NICKNAME     = "NICKNAME"
	NOTE         = "NOTE"
	ORG          = "ORG"
	PHOTO        = "PHOTO"
	PRODID       = "PRODID"
	PROFILE      = "PROFILE"
	RELATED      = "RELATED"
	REV          = "REV"
	ROLE         = "ROLE"
	SORT_STRING  = "SORT-STRING"
	SOUND        = "SOUND"
	SOURCE       = "SOURCE"
	TEL          = "TEL"
	TITLE        = "TITLE"
	TZ           = "TZ"
	UID          = "UID"
	URL          = "URL"
	VERSION      = "VERSION"
	XML          = "XML"
)
