version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/mapaiva/vcard-go

    steps:
      - checkout
      - run: go get -u github.com/golang/lint/golint
      - run: make install
      - run: 
          name: Run linter
          command: make lint
      - run:
          name: Run unit tests
          command: make test
