version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    environment:
      - TEST_RESULTS: "/tmp/test-results"

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get github.com/jstemmer/go-junit-report
      - run: go get github.com/golang/lint
      - run: 
          name: Run linter
          command: make lint
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: ${TEST_RESULTS}
